In [1]:
!pip install scikit_learn

Requirement already satisfied: scikit_learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit_learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit_learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit_learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit_learn) (3.6.0)

In [2]:
from sklearn.datasets import fetch_california_housing

In [3]:
california= fetch_california_housing(as_frame=True)
california

{'data':        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
 0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
 1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
 2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
 3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
 4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
 ...       ...       ...       ...        ...         ...       ...       ...
 20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48
 20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49
 20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43
 20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43
 20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37

        Longitude
 0        -122.23
 1        -122.22
 2        -122.24
 3        -122.25
 4        -122.25
 ...          ...
 20635    -121.09
 20636    -121.21
 20637    -121.22
 20638    -121.32
 20639    -121.24

 [20640 rows x 8 columns],
 'target': 0        4.526
 1        3.585
 2        3.521
 3        3.413
 4        3.422
          ...
 20635    0.781
 20636    0.771
 20637    0.923
 20638    0.847
 20639    0.894
 Name: MedHouseVal, Length: 20640, dtype: float64,
 'frame':        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
 0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
 1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
 2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
 3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
 4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
 ...       ...       ...       ...        ...         ...       ...       ...
 20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48
 20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49
 20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43
 20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43
 20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37

        Longitude  MedHouseVal
 0        -122.23        4.526
 1        -122.22        3.585
 2        -122.24        3.521
 3        -122.25        3.413
 4        -122.25        3.422
 ...          ...          ...
 20635    -121.09        0.781
 20636    -121.21        0.771
 20637    -121.22        0.923
 20638    -121.32        0.847
 20639    -121.24        0.894

 [20640 rows x 9 columns],
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33 (1997) 291-297\n'}

In [5]:
california_df=california.frame
california_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [ ]:
california_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [ ]:
california_df["Population"]

0         322.0
1        2401.0
2         496.0
3         558.0
4         565.0
          ...
20635     845.0
20636     356.0
20637    1007.0
20638     741.0
20639    1387.0
Name: Population, Length: 20640, dtype: float64

In [6]:
def data_diagnostics(df):
  d={
      "missing_values":df.isnull().sum(),
      "data_types":df.dtypes,
      "numeric_stats":df.describe()
     }
  return d

In [7]:
result=data_diagnostics(california_df)
result

{'missing_values': MedInc         0
 HouseAge       0
 AveRooms       0
 AveBedrms      0
 Population     0
 AveOccup       0
 Latitude       0
 Longitude      0
 MedHouseVal    0
 dtype: int64,
 'data_types': MedInc         float64
 HouseAge       float64
 AveRooms       float64
 AveBedrms      float64
 Population     float64
 AveOccup       float64
 Latitude       float64
 Longitude      float64
 MedHouseVal    float64
 dtype: object,
 'numeric_stats':              MedInc      HouseAge      AveRooms     AveBedrms    Population  \
 count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000
 mean       3.870671     28.639486      5.429000      1.096675   1425.476744
 std        1.899822     12.585558      2.474173      0.473911   1132.462122
 min        0.499900      1.000000      0.846154      0.333333      3.000000
 25%        2.563400     18.000000      4.440716      1.006079    787.000000
 50%        3.534800     29.000000      5.229129      1.048780   1166.000000
 75%        4.743250     37.000000      6.052381      1.099526   1725.000000
 max       15.000100     52.000000    141.909091     34.066667  35682.000000

            AveOccup      Latitude     Longitude   MedHouseVal
 count  20640.000000  20640.000000  20640.000000  20640.000000
 mean       3.070655     35.631861   -119.569704      2.068558
 std       10.386050      2.135952      2.003532      1.153956
 min        0.692308     32.540000   -124.350000      0.149990
 25%        2.429741     33.930000   -121.800000      1.196000
 50%        2.818116     34.260000   -118.490000      1.797000
 75%        3.282261     37.710000   -118.010000      2.647250
 max     1243.333333     41.950000   -114.310000      5.000010  }

In [ ]:
california_df.isnull().sum()

MedInc         0
HouseAge       0
AveRooms       0
AveBedrms      0
Population     0
AveOccup       0
Latitude       0
Longitude      0
MedHouseVal    0
dtype: int64

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("laptop_data.csv")
df

,Brand,Model,Age(Years),Condition,Specifications,Original_Price,Battery Life (hrs),Storage Type,Screen Size (inches)
0,Dell,XPS 13,3,Good,Intel i7,120000,8,SSD,13.3
1,HP,EliteBook 840,4,Fair,Intel i5,80000,5,HDD,14.0
2,Apple,MacBook Air,3,Excellent,Apple M1,100000,15,SSD,13.3
3,Lenovo,IdeaPad Flex 5,3,Good,AMD Ryzen 5,60000,7,SSD,14.0
4,Samsung,Notebook 7,5,Fair,Intel i5,70000,4,HDD,15.6
...,...,...,...,...,...,...,...,...,...
87,HP,Chromebook 14,4,Fair,Intel Celeron,20000,10,HDD,14.0
88,Apple,MacBook Pro,2,Excellent,Intel i7,170000,8,SSD,13.3
89,Asus,VivoBook S15,3,Good,Intel i5,80000,8,SSD,15.6
90,Acer,Spin 5,4,Fair,Intel i7,75000,7,HDD,13.5
91,Lenovo,Legion Y740,3,Good,Intel i7,150000,5,SSD,15.6

In [ ]:
df

,Brand,Model,Age(Years),Condition,Specifications,Original_Price,Battery Life (hrs),Storage Type,Screen Size (inches)
0,Dell,XPS 13,3,Good,Intel i7,120000,8,SSD,13.3
1,HP,EliteBook 840,4,Fair,Intel i5,80000,5,HDD,14.0
2,Apple,MacBook Air,3,Excellent,Apple M1,100000,15,SSD,13.3
3,Lenovo,IdeaPad Flex 5,3,Good,AMD Ryzen 5,60000,7,SSD,14.0
4,Samsung,Notebook 7,5,Fair,Intel i5,70000,4,HDD,15.6
...,...,...,...,...,...,...,...,...,...
87,HP,Chromebook 14,4,Fair,Intel Celeron,20000,10,HDD,14.0
88,Apple,MacBook Pro,2,Excellent,Intel i7,170000,8,SSD,13.3
89,Asus,VivoBook S15,3,Good,Intel i5,80000,8,SSD,15.6
90,Acer,Spin 5,4,Fair,Intel i7,75000,7,HDD,13.5
91,Lenovo,Legion Y740,3,Good,Intel i7,150000,5,SSD,15.6

In [ ]:
df.tail()

,Brand,Model,Age(Years),Condition,Specifications,Original_Price,Battery Life (hrs),Storage Type,Screen Size (inches)
87,HP,Chromebook 14,4,Fair,Intel Celeron,20000,10,HDD,14.0
88,Apple,MacBook Pro,2,Excellent,Intel i7,170000,8,SSD,13.3
89,Asus,VivoBook S15,3,Good,Intel i5,80000,8,SSD,15.6
90,Acer,Spin 5,4,Fair,Intel i7,75000,7,HDD,13.5
91,Lenovo,Legion Y740,3,Good,Intel i7,150000,5,SSD,15.6

In [ ]:
df.head()

,Brand,Model,Age(Years),Condition,Specifications,Original_Price,Battery Life (hrs),Storage Type,Screen Size (inches)
0,Dell,XPS 13,3,Good,Intel i7,120000,8,SSD,13.3
1,HP,EliteBook 840,4,Fair,Intel i5,80000,5,HDD,14.0
2,Apple,MacBook Air,3,Excellent,Apple M1,100000,15,SSD,13.3
3,Lenovo,IdeaPad Flex 5,3,Good,AMD Ryzen 5,60000,7,SSD,14.0
4,Samsung,Notebook 7,5,Fair,Intel i5,70000,4,HDD,15.6

In [ ]:
df.isnull()

,Brand,Model,Age(Years),Condition,Specifications,Original_Price,Battery Life (hrs),Storage Type,Screen Size (inches)
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
87,False,False,False,False,False,False,False,False,False
88,False,False,False,False,False,False,False,False,False
89,False,False,False,False,False,False,False,False,False
90,False,False,False,False,False,False,False,False,False
91,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

Brand                   0
Model                   0
Age(Years)              0
Condition               0
Specifications          0
Original_Price          0
Battery Life (hrs)      0
Storage Type            0
Screen Size (inches)    0
dtype: int64

In [ ]:
def data_diagnostics():
  pass

In [ ]:
def data_diagnostics(df):
  diagnostics={
  "first five data":df.head(),
  "last five data":df.tail(),
  "Missing values":df.isnull().sum()
  }
  return diagnostics

In [ ]:
data_diagnostics(df)

{'first five data':      Brand           Model  Age(Years)  Condition Specifications  \
 0     Dell          XPS 13           3       Good       Intel i7
 1       HP   EliteBook 840           4       Fair       Intel i5
 2    Apple     MacBook Air           3  Excellent       Apple M1
 3   Lenovo  IdeaPad Flex 5           3       Good    AMD Ryzen 5
 4  Samsung      Notebook 7           5       Fair       Intel i5

    Original_Price  Battery Life (hrs) Storage Type  Screen Size (inches)
 0          120000                   8          SSD                  13.3
 1           80000                   5          HDD                  14.0
 2          100000                  15          SSD                  13.3
 3           60000                   7          SSD                  14.0
 4           70000                   4          HDD                  15.6  ,
 'last five data':      Brand          Model  Age(Years)  Condition Specifications  \
 87      HP  Chromebook 14           4       Fair  Intel Celeron
 88   Apple    MacBook Pro           2  Excellent       Intel i7
 89    Asus   VivoBook S15           3       Good       Intel i5
 90    Acer         Spin 5           4       Fair       Intel i7
 91  Lenovo    Legion Y740           3       Good       Intel i7

     Original_Price  Battery Life (hrs) Storage Type  Screen Size (inches)
 87           20000                  10          HDD                  14.0
 88          170000                   8          SSD                  13.3
 89           80000                   8          SSD                  15.6
 90           75000                   7          HDD                  13.5
 91          150000                   5          SSD                  15.6  ,
 'Missing values': Brand                   0
 Model                   0
 Age(Years)              0
 Condition               0
 Specifications          0
 Original_Price          0
 Battery Life (hrs)      0
 Storage Type            0
 Screen Size (inches)    0
 dtype: int64}